### ISSUE TITLE
Make SSMS 22 extension work again

### ISSUE THREAD

**Issue by luisdev** [ErikEJ/SqlCeToolbox#1049]
The https://github.com/ErikEJ/SqlCeToolbox/wiki starts with the "How do I get started using the Toolbox?" topic. The first thing that topic should discuss is what you do with the SQLite_and_SQL_Server_Compact_Toolbox_v4.9.46.vsix file once you have downloaded it. What do you do with that .vsix file? Do you click on it? Do you extract it somewhere? Do you put it somewhere?

**Comment by luisdev** [comment]
And can you use the Toolbox in SQL Server Management Studio? If so, that wiki documentation page should explain how.

**Comment by ErikEJ** [comment]
@luisdev Usage in SSMS is explained here: https://github.com/ErikEJ/SqlCeToolbox

**Comment by ErikEJ** [comment]
Fixed, thanks for the feedback

**Comment by ErikEJ** [comment]
<img width="465" height="86" alt="Image" src="https://github.com/user-attachments/assets/195c8f0e-828c-4ae1-bfdb-60556715a857" />

**Comment by luisdev** [comment]
I still don't see it in SSMS! Guess I should reboot the laptop (and get a drink!)

**Comment by luisdev** [comment]
I downloaded the SQLite_and_SQL_Server_Compact_Toolbox_v4.9.46.vsix file.

I have both SSMS 22 and 21, but I am only using SSMS 22. It's on a Windows 11 Dell laptop with an Intel(R) Core(TM) Ultra 7 165H (1.40 GHz) processor.

**Comment by ErikEJ** [comment]
And did the installer run?

**Comment by ErikEJ** [comment]
@luisdev You downloaded the wrong file! Follow the correct link in the readme to: https://www.vsixgallery.com/extension/d6c77c32-fe4b-4f6d-ad5d-f7b755212760

Download from there is called: "SQL Server Compact and SQLite Toolbox for SSMS v4.9.46.vsix"

**Comment by ErikEJ** [comment]
@luisdev Fixed in 4.9.53 or later, thanks for reporting
