### ISSUE TITLE
Test connection successful and then login error with the same user using SQL auth

### ISSUE THREAD

**Issue by gp1983** [ErikEJ/SqlCeToolbox#298]
The test connection is successful but then when i click on OK it throws an error "Login failed for user xx" 
I'm using visual studio 2017.

![image](https://cloud.githubusercontent.com/assets/26405263/23894799/cdb2dbdc-08a3-11e7-99fb-02ccd2d6c91a.png)
![image](https://cloud.githubusercontent.com/assets/26405263/23894818/ddf0ee62-08a3-11e7-8a05-ff8b18369f94.png)

**Comment by ErikEJ** [comment]
Thanks for reporting this, it is a known issue with SQL authentication and has been fixed in the latest daily build - https://github.com/ErikEJ/SqlCeToolbox

**Comment by gp1983** [comment]
thank you, now It connects without error but I still can't see the Table node, even if I double click on the Data Connections links.. the data source is sql server 2014 SP1.

![image](https://cloud.githubusercontent.com/assets/26405263/23898597/d2aed2a4-08b1-11e7-9b14-9cbcecf7a406.png)

**Comment by ErikEJ** [comment]
That is by design (not being able to see the tables) - there are a number of other tools in Visual Studio to view and manage SQL Server databases, including Server Explorer and SQL Server Object Explorer. You can right click the server name to get a number of Toolbox specific features (like EF Core code generation)
