### ISSUE TITLE
SQLite views - pretty print

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#506]
It would be nice to correctly reproduce the line-feeds when scripting SQL views.
```
CREATE VIEW [vwGroupBibs] AS      SELECT BibFrom, BibTo, idGroup                      FROM GroupBibs;
```
should become (like it happens on the tables):
```
CREATE VIEW [vwGroupBibs] AS
      SELECT BibFrom, BibTo, idGroup
                      FROM GroupBibs;
```

### Steps to reproduce
_Script as CREATE_ on the view's context menu but also in the _Script Database_ commands.

### Further technical details
Toolbox version: 4.7.232.0
Database engine: SQlite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Not sure I understand why you are facing this, I already add newlines !?

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/API/Generator/Generator.cs#L2137

**Comment by ErikEJ** [comment]
Ping?

**Comment by mwallnoefer** [comment]
Ah sorry, forgotten to answer. Yes but in `view.Definition`, do you handle them also there? According to me this is not the case atm.

**Comment by ErikEJ** [comment]
I do not do anything with view.Definition, I just display it as is from the SQLite schema info.

**Comment by ErikEJ** [comment]
Is it a linebreak issue, perhaps?

**Comment by mwallnoefer** [comment]
This means if I use the sqlite3 tool from cmdline I see the view definition in the exactly same manner? I need to re-try this...
With SQLite Personal it is different.

**Comment by ErikEJ** [comment]
Pls try the latest daily and let me know!

**Comment by mwallnoefer** [comment]
I would give it a look but am unable to do so. In the latest daily build at my SQLite connections disappeared (under _Data Connections_). When I try to add a new connection, the configuration dialog pops up, but after clicking on _Close_ it does not appear in the tree - this is strange.

![grafik](https://user-images.githubusercontent.com/7541399/30914571-7275d2c4-a394-11e7-89b5-11ab0d5f1093.png)

**Comment by ErikEJ** [comment]
Could you show me the About dialog in the latest build? Sounds like your DataProvider installation is broken.

**Comment by mwallnoefer** [comment]
![grafik](https://user-images.githubusercontent.com/7541399/30915070-d4ce173c-a395-11e7-910d-86fcb9c076ce.png)

Ah yes. Where do I need to download it?

**Comment by ErikEJ** [comment]
http://system.data.sqlite.org/downloads/1.0.105.2/sqlite-netFx46-setup-bundle-x86-2015-1.0.105.2.exe from http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki

**Comment by ErikEJ** [comment]
Guide here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by mwallnoefer** [comment]
I have tried to follow your instructions but no change in behaviour. But now the SQLite EF6 DBProvider is in the GAC.
![grafik](https://user-images.githubusercontent.com/7541399/30919206-04472dd6-a3a1-11e7-8e11-625ea7137cf5.png)

**Comment by mwallnoefer** [comment]
Now I turned back to the latest stable and everything works again (I can see all SQLite DBs).

![grafik](https://user-images.githubusercontent.com/7541399/30955609-7bc1a6d2-a434-11e7-8b94-b41c95da1976.png)

**Comment by ErikEJ** [comment]
Thanks, I will try to reproduce and provide a fix!

**Comment by ErikEJ** [comment]
Fixed in the latest daily build, thanks for reporting! Could I ask you to try it out an let me know?

**Comment by mwallnoefer** [comment]
Here my answer:
- SQLite DBs show up again, this works Erik!
- The fix works only for the _Script Database_ commands,  but not on _Script as CREATE_ on the single view.
- The indentation is still not correct, first I will check with the cmdline sqlite3 tool and then provide you with an example DB.

**Comment by mwallnoefer** [comment]
_sqlite3_ output: 
```
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE VIEW [vwBibs] AS
WITH RECURSIVE
    [tab] AS(
        SELECT 1 AS [BibFrom],
               10 AS [BibTo]
        UNION ALL
        SELECT [BibFrom] + 1,
               [BibTo]
        FROM   [tab]
        WHERE  [BibFrom] < [BibTo]
    )
SELECT [BibFrom]
FROM   [tab];
COMMIT;
```

[test.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1343405/test.zip)

**Comment by mwallnoefer** [comment]
@ErikEJ, have you managed to figure out something?

**Comment by ErikEJ** [comment]
Yes, it was an issue with the System.Data.Sqlite implementation of GetSchema("Views") !
This line of code removes any formatting!

              strItem = rd.GetString(4).Replace('\r', ' ').Replace('\n', ' ').Replace('\t', ' ');

Changed to get the raw defintion now - fixed in latest build, please let me know if it works for you.

**Comment by mwallnoefer** [comment]
It works, wonderful!
