### ISSUE TITLE
Enable support for SSMS 18.0

### ISSUE THREAD

**Issue by chojrak11** [ErikEJ/SqlCeToolbox#755]
Hi! Please release a version that will install in SSMS 18.0 (currently at beta 5).
Thanks in advance!

**Comment by ErikEJ** [comment]
I will enable that when SSMS 18 is no longer in beta

**Comment by duncansmart** [comment]
SSMS 18 is out of beta now: https://cloudblogs.microsoft.com/sqlserver/2019/04/24/sql-server-management-studio-ssms-18-0-released-for-general-availability/

**Comment by ErikEJ** [comment]
Thanks, I will wiat for the dust to settle, but will consider a community PR for it.

**Comment by IoTFier** [comment]
Hi @ErikEJ , SSMS 18.1 is out. Will you please help us on this issue?
I am getting following error when tried to install your extn in SSMS 18.1
![image](https://user-images.githubusercontent.com/26844611/59894968-4270fa80-93a8-11e9-9278-1786d79b00ce.png)


Thanks

**Comment by win32nipuh** [comment]
I have tried: it installed and works ok in SSMS 18.1

**Comment by ErikEJ** [comment]
@win32nipuh Interesting!

**Comment by IoTFier** [comment]
@win32nipuh , @ErikEJ -

Assumming SSMS 17 may be causing issue while having SSMS 18.1 SxS, I uninstalled SSMS 17 and tried to install this extension again... Now facing another issue -

![image](https://user-images.githubusercontent.com/26844611/60351860-48f50880-998c-11e9-9d3f-1fde27fe00bc.png)

**Comment by ErikEJ** [comment]
@IoTFier The extension does not work with SSMS 18 at all, not sure why you are expecting that?

**Comment by IoTFier** [comment]
@ErikEJ , are you suggesting that it is valid only upto SSMS 17 ? 
I am moving to SSMS 18 because it is back on supporting diagram creation.

Interestingly, I couldn't get it installed on SSMS 17 as well.

Please help us with a version for SSMS 18+.

Thanks

**Comment by ErikEJ** [comment]
@iotfier why do you need it so badly?

I have quite few downloads of this edition, and it has very few features.

**Comment by ErikEJ** [comment]
Did you try the command line install described in the readme?

**Comment by IoTFier** [comment]
> Did you try the command line install described in the readme?

Yes, I did. It results in the same "Install Failed" error as I posted the screenshot above

**Comment by ErikEJ** [comment]
That makes sense since you only have SSMS 18 installed, and it is not supported!
Again: @IoTFier why do you need it so badly?
I have quite few downloads of this edition, and it has very few features.

**Comment by IoTFier** [comment]
> That makes sense since you only have SSMS 18 installed, and it is not supported!
> Again: @IoTFier why do you need it so badly?
> I have quite few downloads of this edition, and it has very few features.

Why I need it so badly ..? because 
1. as I mentioned above SSMS 18 has brought back the Diagram feature 
2. per my issue https://github.com/ErikEJ/SqlCeToolbox/issues/790 this vsix doesn't support diagramming when installed in the VS

That's where I thought of deviating from VS version of this extension and bring it directly into SSMS, which in any case much comprehensive functional tool to work with for database(s) needs instead of having to deal with it inside VS

Hope this answers my intent.

Would really appreciate your help.

Thanks.

**Comment by ErikEJ** [comment]
@IoTFier 
1, The diagram feature in SSMS has nothing to do with the diagram feature in this tool - use the "Create database graph (DGML)" option in the VS extension for that.

2. The VS extension DOES support diagrams from SQLite, the feature is called "Create database graph" !

**Comment by IoTFier** [comment]
Hi @ErikEJ , thank you.

Any recommendation on extn / tool to open the dgml file?

Regarding diagram - I thought dragging and dropping my sqlite tables on the diagram palette inside SSMS will be lot interactive and easier than jumping thru the hoops of finding another set of tooling / vsix / OSS to interact with your vsix.

**Comment by ErikEJ** [comment]
>> Any recommendation on extn / tool to open the dgml file?

Visual Studio!

**Comment by IoTFier** [comment]
> > > Any recommendation on extn / tool to open the dgml file?
> 
> Visual Studio!

VS 2019 is showing textual information from .dgml and not visual.

**Comment by ErikEJ** [comment]
You need to add the DGML editor component:

![image](https://user-images.githubusercontent.com/4169187/60384095-f265f800-9a79-11e9-9067-b7bf76c763c9.png)

**Comment by IoTFier** [comment]
Wonderful ! Thank you @ErikEJ  
This is a great interim help. 

But to be honest, I will be still waiting for your extension to work in SSMS 18+ so that I could use proper ER diagram feature of SSMS. 

Thank you.

**Comment by ErikEJ** [comment]
You do not need my extension to do that

**Comment by IoTFier** [comment]
I do. SSMS out of the box doesn't have a feature / an ODBC driver to connect with Sqlite (to my knowledge). I tried that in Visio, but MS has stopped supporting reverse engg of DB in Visio since Visio 2016.

**Comment by ErikEJ** [comment]
Ah, you are waiting for the diagram feature in the SSMS edition of my extension - that is never going to happen.

**Comment by IoTFier** [comment]
@ErikEJ ... nope. that's not what I said.

**Comment by ErikEJ** [comment]
Ok, then please elaborate on what you DID say.

**Comment by IoTFier** [comment]
Per my understanding and assumption - based on the way your extn works in VS, I was hoping that if it could work the same way (regardless of DGML feature) in SSMS where I could connect my sql to the sqlite database file , then, I could try dragging tables into the diagram panel which is back in SSMS 18

But, I didn't even get to try that yet as there is no SSMS 18+ compatible version of your extension.

If I am still not clear, then, that's ok. We can leave it here.

Thank you for everything.

**Comment by ErikEJ** [comment]
You are clear, but what you are asking for is never going to happen. The diagram feature in SSMD only works with SQL Server.

**Comment by IoTFier** [comment]
But what if your extn or any other were to provide same data to the interface diagram panel is looking for ? 
I don't know underlying details on that .. but that's ok.  

I wished MS had provided this out of the box capability where SSMS could be used for other DBs as well especially Sqlite.

Thank you for the interaction and for your patience to understand my thoughts.
Much appreciated.

**Comment by glowworms** [comment]
Hi ErikEJ,

What can we do to help you to get SSMSToolbox to work on SSMS 18?
Or is there any workaround to get this extension to install on SSMS 18?
Currently I have to have SSMS 17 and 18 running side-by-side.

At the time of writing this message, SSMS is on version 18.3.1.

Thank you

**Comment by ErikEJ** [comment]
@glowworms You could update the dependencies and submit a PR?

**Comment by ErikEJ** [comment]
@glowworms I only see a single upvote for this, btw

**Comment by mzhukovs** [comment]
Would be great fof v18 support - this is a really nice extension.

**Comment by IoTFier** [comment]
@ErikEJ - you got 5 votes now in last 19 days. Mind changed ? :)

**Comment by ErikEJ** [comment]
I am very open to PRs! 😄

**Comment by ErikEJ** [comment]
WIP

**Comment by ErikEJ** [comment]
Fixed in latest daily build, would be grateful if you could try it out.

**Comment by IoTFier** [comment]
@ErikEJ , I will test it and let you know.

**Comment by IoTFier** [comment]
Tried to install the extension from the [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolboxforSSMS), and got following error -
![image](https://user-images.githubusercontent.com/26844611/68087318-4dd63700-fe1a-11e9-8f56-d603d3cbd607.png)

From the log file ..
11/3/2019 9:11:40 AM - Signature Details...
11/3/2019 9:11:40 AM - 	Extension is not signed.
11/3/2019 9:11:40 AM - 
11/3/2019 9:11:40 AM - Searching for applicable products...
11/3/2019 9:11:40 AM - Found installed product - Global Location
11/3/2019 9:11:40 AM - Found installed product - Visual Studio Community 2017
11/3/2019 9:11:40 AM - Found installed product - Visual Studio Community 2019
11/3/2019 9:11:40 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by ErikEJ** [comment]
It is not published yet! You must install the latest daily build - https://github.com/ErikEJ/SqlCeToolbox#sql-server-management-studio-ssms-18x-extension

**Comment by IoTFier** [comment]
> It is not published yet! You must install the latest daily build - https://github.com/ErikEJ/SqlCeToolbox#sql-server-management-studio-ssms-18x-extension

Hi @ErikEJ, I think I did download the dailybuild from the link as shown below, but still got the error as shown in my note above ... pic towards the bottom. Please let me know if I am clicking on the wrong link.

![image](https://user-images.githubusercontent.com/26844611/68088328-c8f01b00-fe23-11e9-9b84-926161b56d01.png)

**Comment by ErikEJ** [comment]
How did you do the install? From command line as documented or just by double-click?

**Comment by IoTFier** [comment]
> How did you do the install? From command line as documented or just by double-click?

Double-click.

**Comment by ErikEJ** [comment]
Follow the documentation and use the command line, pls. That's why the docs are there!

**Comment by ErikEJ** [comment]
notice: **If you have trouble installing the SSMS extension, try the following command line:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\vsixinstaller.exe" "full path to extension.vsix"**

**Comment by IoTFier** [comment]
> Follow the documentation and use the command line, pls. That's why the docs are there!

Hi @ErikEJ , I really appreciate your help and support. I followed your doc and it is giving the same error / message on using CLI. It doesn't detect my VS 2019 Community set up and SSMS 18.3.1 set up.

**Comment by glowworms** [comment]
Hi, Erik,

I have tried to install the new extension also from the latest build and I get this error:
I tried these things:
 - install using the command line
 - install by double-clicking
 - I have uninstalled the previous versions
 - I have used the latest version of VSIXInstaller.exe


![2019-11-04_074835](https://user-images.githubusercontent.com/7495599/68092499-86881600-fed7-11e9-89ec-b6c1c5ca63e6.png)

In the log files, it fails at this point:

`Skipping 'C:\Users\{myusername}\AppData\Local\Microsoft SDKs' as it doesn't exist
The extension with ID 'd6c77c32-fe4b-4f6d-ad5d-f7b755212760' is not installed to Visual Studio Enterprise 2017.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.IntializePackages()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisitesInternal(IInstallableExtension extension, ICollection`1 installedPackages, ICollection`1 installablePackages, ICollection`1 unresolvedReferences)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetPrerequisites(IInstallableExtension extension, IEnumerable`1& installedPackages, IEnumerable`1& installablePackages, IEnumerable`1& unresolvedReferences)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)`


These are the things I have installed on my machine:
 - VS 2017 Enterprise
 - SSMS 17.9.1
 - SSMS 18.3.1

**Comment by IoTFier** [comment]
Hi @glowworms , @ErikEJ  -

I am using VS Community 2019, 2017 Editions and SSMS 18.3.1

**Comment by ErikEJ** [comment]
I will check the installer issues

**Comment by ErikEJ** [comment]
I have published installation instructions here: https://github.com/ErikEJ/SqlCeToolbox/blob/master/README.md#installing-the-ssms-18-extension

**Comment by IoTFier** [comment]
Hi @ErikEJ , thank you. I tried it with admin privilege and still getting the error access denied.

![image](https://user-images.githubusercontent.com/26844611/68150543-8e5eaf00-ff05-11e9-8f7a-6708fe3c2705.png)
![image](https://user-images.githubusercontent.com/26844611/68150573-9f0f2500-ff05-11e9-9149-a5c697e971fe.png)

**Comment by ErikEJ** [comment]
Maybe delete all files and try again. Also shut down SSMS

**Comment by glowworms** [comment]
Thanks Erik,

I can confirm that the extraction using the Admin Command Prompt worked for me for SSMS 18.3.1

![2019-11-05_062210](https://user-images.githubusercontent.com/7495599/68155030-9ca7dc00-ff94-11e9-8d1e-f8d4c3f99fc7.png)
(Note: I had renamed my extension.vsix to SSMSToolbox.vsix)


The extension can be accessed via the Tools menu now.
![2019-11-05_062453](https://user-images.githubusercontent.com/7495599/68155346-41c2b480-ff95-11e9-9b8b-ea8e50e616b5.png)

Thanks for your help.

**Comment by IoTFier** [comment]
Hi @glowworms, I am able to extract extension.vsix and can see 48 files, but I don't see the extension in SSMS (BTW - I upgraded mine to 18.4 today - which I believe shouldn't matter - @ErikEJ  ??

did you follow any other step before getting to see that extension in SSMS 18.3 ?

thank you.

**Comment by glowworms** [comment]
And I can also confirm that I've upgraded my SSMS to 18.4 and every continued to work without doing anything extra..

Thanks Erik!

**Comment by ErikEJ** [comment]
You are both welcome, and thanks for your patience!
